version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: currency_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:example@db/currency_db
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"